services:
  - type: web
    name: oppdrag-app
    env: node
    plan: free
    buildCommand: npm install && cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true 